'use client';
import { useMemo,useState } from 'react';
import type { LiveTable } from '@/lib/types'; import { computedStatus,presentTotal } from '@/lib/live'; import { supabase } from '@/lib/supabase/client';
const colors={free:'bg-zinc-100 text-zinc-950',reserved:'bg-blue-500',occupied:'bg-emerald-500',light_overload:'bg-orange-500',overload:'bg-red-600',unavailable:'bg-zinc-950 ring-1 ring-zinc-500'};
const labels={free:'⚪ Libre',reserved:'🔵 Réservée',occupied:'🟢 Occupée',light_overload:'🟠 Surcharge légère',overload:'🔴 Surcharge',unavailable:'⚫ Indisponible'};
export function VenueMap({tables,editable=false,onSelect}:{tables:LiveTable[],editable?:boolean,onSelect?:(table:LiveTable)=>void}){const [editing,setEditing]=useState(false);const [selected,setSelected]=useState<LiveTable|null>(null);const [zoneId,setZoneId]=useState('all');const shown=useMemo(()=>zoneId==='all'?tables:tables.filter(t=>t.zone_id===zoneId),[tables,zoneId]);const zones=[...new Map(tables.map(t=>[t.zone.id,t.zone])).values()].sort((a,b)=>a.display_order-b.display_order);
 async function move(t:LiveTable,e:React.DragEvent<HTMLButtonElement>){if(!editing)return;const box=e.currentTarget.parentElement!.getBoundingClientRect();const position_x=Math.max(0,Math.min(100,((e.clientX-box.left)/box.width)*100));const position_y=Math.max(0,Math.min(100,((e.clientY-box.top)/box.height)*100));await supabase.from('tables').update({position_x,position_y}).eq('id',t.id);}
 function select(t:LiveTable){setSelected(t);onSelect?.(t)}
 return <section className="panel overflow-hidden"><div className="flex flex-wrap items-center justify-between gap-2 p-4"><div><h2 className="font-bold">PLAN DE SALLE</h2><p className="text-xs text-zinc-400">Pont Alexandre III · temps réel</p></div>{editable&&<button onClick={()=>setEditing(!editing)} className="rounded-lg bg-zinc-700 px-3 py-2 text-sm">{editing?'Terminer':'Modifier le plan'}</button>}</div><div className="flex gap-2 overflow-x-auto px-4 pb-3"><button onClick={()=>setZoneId('all')} className={`whitespace-nowrap rounded-full px-3 py-2 text-sm ${zoneId==='all'?'bg-fuchsia-600':'bg-zinc-800'}`}>Plan complet</button>{zones.map(z=><button onClick={()=>setZoneId(z.id)} className={`whitespace-nowrap rounded-full px-3 py-2 text-sm ${zoneId===z.id?'bg-fuchsia-600':'bg-zinc-800'}`} key={z.id}>{z.name}</button>)}</div><div className={zoneId==='all'?'overflow-auto':'overflow-hidden'}><div onDragOver={e=>e.preventDefault()} className={`relative bg-zinc-950 ${zoneId==='all'?'aspect-[1.72] min-w-[1000px]':'h-[500px] min-w-0'}`} style={{backgroundImage:"linear-gradient(rgba(0,0,0,.30),rgba(0,0,0,.30)), url('/venue-plan-reference.jpeg')",backgroundSize:zoneId==='all'?'cover':'172% auto',backgroundPosition:zoneId==='all'?'center':zoneId===zones[0]?.id?'right top':zoneId===zones[1]?.id?'left bottom':zoneId===zones[2]?.id?'center bottom':'right bottom'}}>{shown.map(t=>{const status=computedStatus(t);const localX=zoneId==='all'?t.position_x:zoneId===zones[0]?.id?(t.position_x-75)*4:zoneId===zones[1]?.id?t.position_x*4:zoneId===zones[2]?.id?(t.position_x-45)*4:(t.position_x-72)*4;const localY=zoneId==='all'?t.position_y:zoneId===zones[0]?.id?t.position_y*2.7:(t.position_y-70)*3.1;return <button draggable={editing} onDragEnd={e=>move(t,e)} onClick={()=>select(t)} key={t.id} style={{left:`${localX}%`,top:`${localY}%`}} className={`absolute z-10 -translate-x-1/2 -translate-y-1/2 rounded-full ${colors[status]} h-9 w-9 text-[9px] font-black shadow-lg ring-2 ring-white/80 sm:h-11 sm:w-11 sm:text-[11px]`}>T{t.number}<br/>{presentTotal(t)}</button>})}</div></div>{selected&&<div className="m-4 rounded-xl border border-zinc-700 bg-zinc-950 p-4 text-sm"><div className="flex justify-between"><b className="text-lg">TABLE {selected.number}</b><button onClick={()=>setSelected(null)}>×</button></div><div className="mt-2 grid grid-cols-2 gap-2 text-zinc-300"><span>CDR : {selected.head_waiter?`${selected.head_waiter.first_name} ${selected.head_waiter.last_name}`:'—'}</span><span>Zone : {selected.zone.name}</span><span>Réservation : {selected.reservation?.reserved_people??0}</span><span>Présents : {selected.occupancy?.present_people??0}</span><span>Invités : {selected.occupancy?.extra_guests??0}</span><b>Total : {presentTotal(selected)}</b></div><p className="mt-2 font-semibold">{labels[computedStatus(selected)]}</p></div>}<p className="px-4 pb-4 text-xs text-zinc-400">⚪ Libre · 🔵 Réservée · 🟢 1–7 · 🟠 8–9 · 🔴 10+ · ⚫ Indisponible</p></section>}
